import assert from "node:assert/strict";
import test from "node:test";
import {
  A1_NOISY_GATE,
  NOISY_RULE_IDS,
  auditMustHit,
  auditTuningScene,
  batchTemplatePaths,
  decideGoldenQuality,
  headerLooksGenerated,
  isCodegenPath,
  isHoldoutScene,
  isTestPath,
  loadTuningScenes,
  mavenModuleOf,
  noisyRate,
  sampleTuningScenes
} from "./audit-golden-quality.mjs";

const MODULE_ROOTS = [
  "yudao-module-mes",
  "yudao-module-system",
  "yudao-module-infra",
  "yudao-module-wms",
  "yudao-framework"
];

function scene(id, mustHit, extra = {}) {
  return {
    id,
    evaluationSplit: extra.evaluationSplit ?? "tuning",
    anchor: { file: extra.anchor ?? mustHit[0] },
    golden: { mustHit }
  };
}

test("six NOISY rules are frozen", () => {
  assert.deepEqual([...NOISY_RULE_IDS], [
    "mustHitGt8",
    "testInMustHit",
    "codegenShareGe50",
    "modulesGe4",
    "anchorOutsideDepNeighborhood",
    "mergeOrDiffGt30"
  ]);
  assert.equal(A1_NOISY_GATE, 0.3);
});

test("mustHitGt8 positive and negative", () => {
  const files = Array.from({ length: 9 }, (_, index) => `yudao-module-mes/src/main/java/A${index}.java`);
  const pos = auditMustHit(files, { moduleRoots: MODULE_ROOTS, anchorFile: files[0] });
  assert.equal(pos.reasons.includes("mustHitGt8"), true);
  const neg = auditMustHit(files.slice(0, 8), { moduleRoots: MODULE_ROOTS, anchorFile: files[0] });
  assert.equal(neg.reasons.includes("mustHitGt8"), false);
});

test("testInMustHit positive and negative", () => {
  const pos = auditMustHit([
    "yudao-module-wms/src/main/java/WmsInventoryMapper.java",
    "yudao-module-wms/src/test/java/WmsInventoryServiceImplTest.java"
  ], { moduleRoots: MODULE_ROOTS, anchorFile: "yudao-module-wms/src/main/java/WmsInventoryMapper.java" });
  assert.equal(isTestPath("yudao-module-wms/src/test/java/WmsInventoryServiceImplTest.java"), true);
  assert.equal(pos.reasons.includes("testInMustHit"), true);
  const named = auditMustHit([
    "yudao-module-wms/src/main/java/FooTest.java"
  ], { moduleRoots: MODULE_ROOTS, anchorFile: "yudao-module-wms/src/main/java/FooTest.java" });
  assert.equal(named.reasons.includes("testInMustHit"), true);
  const neg = auditMustHit([
    "yudao-module-wms/src/main/java/WmsInventoryMapper.java"
  ], { moduleRoots: MODULE_ROOTS, anchorFile: "yudao-module-wms/src/main/java/WmsInventoryMapper.java" });
  assert.equal(neg.reasons.includes("testInMustHit"), false);
});

test("codegenShareGe50 positive and negative", () => {
  const codegenDir = [
    "yudao-module-infra/src/main/java/codegen/A.java",
    "yudao-module-infra/src/main/java/codegen/B.java",
    "yudao-module-infra/src/main/java/service/C.java"
  ];
  const posPath = auditMustHit(codegenDir, {
    moduleRoots: MODULE_ROOTS,
    anchorFile: codegenDir[2]
  });
  assert.equal(isCodegenPath("yudao-module-infra/src/main/java/codegen/A.java"), true);
  assert.equal(posPath.reasons.includes("codegenShareGe50"), true);

  const sameDir = [
    "yudao-module-mes/src/main/java/vo/A.java",
    "yudao-module-mes/src/main/java/vo/B.java",
    "yudao-module-mes/src/main/java/vo/C.java",
    "yudao-module-mes/src/main/java/vo/D.java",
    "yudao-module-mes/src/main/java/vo/E.java"
  ];
  const batch = batchTemplatePaths(sameDir);
  assert.equal(batch.size, 5);
  const posBatch = auditMustHit(sameDir.slice(0, 4), {
    moduleRoots: MODULE_ROOTS,
    anchorFile: sameDir[0],
    batchPaths: batch
  });
  assert.equal(posBatch.reasons.includes("codegenShareGe50"), true);

  const entityDo = [
    "yudao-module-mes/src/main/java/dal/dataobject/FooDO.java",
    "yudao-module-mes/src/main/java/dal/dataobject/BarDO.java",
    "yudao-module-mes/src/main/java/dal/dataobject/BazDO.java",
    "yudao-module-mes/src/main/java/dal/dataobject/QuxDO.java",
    "yudao-module-mes/src/main/java/dal/dataobject/NorfDO.java"
  ];
  const doBatch = batchTemplatePaths(entityDo);
  assert.equal(doBatch.size, 0);
  const negDo = auditMustHit(entityDo, {
    moduleRoots: MODULE_ROOTS,
    anchorFile: entityDo[0],
    batchPaths: doBatch
  });
  assert.equal(negDo.reasons.includes("codegenShareGe50"), false);

  assert.equal(headerLooksGenerated("/* Generated by MyBatis Plus Generator */\npackage x;\n"), true);
  const headerPos = auditMustHit(
    ["yudao-module-mes/src/main/java/A.java", "yudao-module-mes/src/main/java/B.java"],
    {
      moduleRoots: MODULE_ROOTS,
      anchorFile: "yudao-module-mes/src/main/java/A.java",
      generatedHeaders: new Set(["yudao-module-mes/src/main/java/A.java"])
    }
  );
  assert.equal(headerPos.reasons.includes("codegenShareGe50"), true);

  const four = sameDir.slice(0, 4);
  const tooSmall = batchTemplatePaths(four);
  assert.equal(tooSmall.size, 0);
  const neg = auditMustHit(four, {
    moduleRoots: MODULE_ROOTS,
    anchorFile: four[0],
    batchPaths: tooSmall
  });
  assert.equal(neg.reasons.includes("codegenShareGe50"), false);
});

test("modulesGe4 positive and negative", () => {
  const pos = auditMustHit([
    "yudao-module-mes/src/A.java",
    "yudao-module-system/src/B.java",
    "yudao-module-infra/src/C.java",
    "yudao-module-wms/src/D.java"
  ], { moduleRoots: MODULE_ROOTS, anchorFile: "yudao-module-mes/src/A.java" });
  assert.equal(pos.reasons.includes("modulesGe4"), true);
  assert.equal(mavenModuleOf("yudao-module-mes/src/A.java", MODULE_ROOTS), "yudao-module-mes");
  const neg = auditMustHit([
    "yudao-module-mes/src/A.java",
    "yudao-module-system/src/B.java",
    "yudao-module-infra/src/C.java"
  ], { moduleRoots: MODULE_ROOTS, anchorFile: "yudao-module-mes/src/A.java" });
  assert.equal(neg.reasons.includes("modulesGe4"), false);
});

test("anchorOutsideDepNeighborhood positive and negative", () => {
  const deps = {
    "yudao-module-mes": ["yudao-module-system"],
    "yudao-module-system": ["yudao-module-infra"]
  };
  const pos = auditMustHit(
    ["yudao-module-mes/src/A.java", "yudao-module-system/src/B.java"],
    {
      moduleRoots: MODULE_ROOTS,
      moduleDeps: deps,
      anchorFile: "yudao-module-wms/src/C.java"
    }
  );
  assert.equal(pos.reasons.includes("anchorOutsideDepNeighborhood"), true);
  const neg = auditMustHit(
    ["yudao-module-mes/src/A.java", "yudao-module-system/src/B.java"],
    {
      moduleRoots: MODULE_ROOTS,
      moduleDeps: deps,
      anchorFile: "yudao-module-mes/src/A.java"
    }
  );
  assert.equal(neg.reasons.includes("anchorOutsideDepNeighborhood"), false);
  const viaDep = auditMustHit(
    ["yudao-module-mes/src/A.java"],
    {
      moduleRoots: MODULE_ROOTS,
      moduleDeps: deps,
      anchorFile: "yudao-module-system/src/B.java"
    }
  );
  assert.equal(viaDep.reasons.includes("anchorOutsideDepNeighborhood"), false);
});

test("mergeOrDiffGt30 positive and negative", () => {
  const files = ["yudao-module-mes/src/A.java"];
  const merge = auditMustHit(files, { moduleRoots: MODULE_ROOTS, anchorFile: files[0], isMerge: true, changedFileCount: 2 });
  assert.equal(merge.reasons.includes("mergeOrDiffGt30"), true);
  const big = auditMustHit(files, { moduleRoots: MODULE_ROOTS, anchorFile: files[0], isMerge: false, changedFileCount: 31 });
  assert.equal(big.reasons.includes("mergeOrDiffGt30"), true);
  const neg = auditMustHit(files, { moduleRoots: MODULE_ROOTS, anchorFile: files[0], isMerge: false, changedFileCount: 14 });
  assert.equal(neg.reasons.includes("mergeOrDiffGt30"), false);
});

test("holdout evaluationSplit rows are not consumed", () => {
  const jsonl = [
    JSON.stringify(scene("tune-1", ["yudao-module-mes/src/A.java", "yudao-module-mes/src/B.java"])),
    JSON.stringify(scene("hold-secret", [
      "HOLD_OUT_SECRET.java",
      ...Array.from({ length: 9 }, (_, index) => `yudao-module-mes/src/H${index}.java`)
    ], { evaluationSplit: "holdout", anchor: "HOLD_OUT_SECRET.java" })),
    JSON.stringify({
      id: "lishuedu-exam-score-export-cross-module-holdout",
      golden: { mustHit: ["src/H.java"] }
    })
  ].join("\n");
  const loaded = loadTuningScenes(jsonl);
  assert.equal(loaded.holdoutSkipped, 2);
  assert.equal(loaded.tuning.length, 1);
  assert.equal(loaded.tuning[0].id, "tune-1");
  assert.equal(JSON.stringify(loaded.tuning).includes("HOLD_OUT_SECRET"), false);
  assert.equal(isHoldoutScene({ evaluationSplit: "holdout", id: "x" }), true);
  assert.equal(isHoldoutScene({ id: "paper-task-claim-iam-holdout" }), true);
  const labels = loaded.tuning.map(row => auditTuningScene(row, { moduleRoots: MODULE_ROOTS }));
  assert.equal(JSON.stringify(labels).includes("HOLD_OUT_SECRET"), false);
  assert.equal(labels[0].noisy, false);
});

test("decideGoldenQuality uses 30% or 2x control when rules are too strict", () => {
  const trusted = decideGoldenQuality({ ruoyiNoisyRate: 0.2, controlNoisyRates: [0.1, 0.1, 0.1] });
  assert.equal(trusted.decision, "GOLDEN_TRUSTED");
  assert.equal(trusted.ruleTooStrict, false);
  const noisy = decideGoldenQuality({ ruoyiNoisyRate: 0.4, controlNoisyRates: [0.1, 0.1, 0.1] });
  assert.equal(noisy.decision, "GOLDEN_NOISY");
  const strictTrusted = decideGoldenQuality({ ruoyiNoisyRate: 0.5, controlNoisyRates: [0.4, 0.4, 0.4] });
  assert.equal(strictTrusted.ruleTooStrict, true);
  assert.equal(strictTrusted.decision, "GOLDEN_TRUSTED");
  const strictNoisy = decideGoldenQuality({ ruoyiNoisyRate: 0.9, controlNoisyRates: [0.4, 0.4, 0.4] });
  assert.equal(strictNoisy.decision, "GOLDEN_NOISY");
  assert.equal(noisyRate([{ noisy: true }, { noisy: false }, { noisy: true }]), 2 / 3);
  const sampled = sampleTuningScenes([{ id: "b" }, { id: "a" }, { id: "c" }], 2);
  assert.deepEqual(sampled.map(row => row.id), ["a", "b"]);
});
