// input: dist/build-stamp.json generated by npm run build.
// output: Runtime build metadata for status and benchmark output.
// pos: Small guard against installed-runtime drift.
import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { resourceDefaults } from "./resource-defaults.js";

export type RuntimeBuildInfo = {
  gitSha: string;
  generatedAt: string;
  defaults: Record<string, unknown>;
  defaultsFingerprint: string;
  stampPath?: string;
  missing?: boolean;
};

export function readRuntimeBuild(stampPath = path.join(path.dirname(fileURLToPath(import.meta.url)), "build-stamp.json")): RuntimeBuildInfo {
  if (existsSync(stampPath)) {
    try {
      const parsed = JSON.parse(readFileSync(stampPath, "utf8")) as RuntimeBuildInfo;
      return { ...parsed, stampPath };
    } catch {
      // Fall through to live defaults; status should still be useful if the stamp is corrupt.
    }
  }
  const defaults = resourceDefaults();
  const compactDefaults = {
    idleTtlMs: defaults.idleTtlMs,
    importConcurrency: defaults.importConcurrency,
    jdtlsXmx: defaults.jdtlsXmx,
    maxActiveRepos: defaults.maxActiveRepos
  };
  return {
    gitSha: "unknown",
    generatedAt: new Date(0).toISOString(),
    defaults: compactDefaults,
    defaultsFingerprint: fingerprint(compactDefaults),
    stampPath,
    missing: true
  };
}

function fingerprint(value: unknown): string {
  return createHash("sha1").update(JSON.stringify(value)).digest("hex").slice(0, 12);
}
